### ISSUE TITLE
crawl everything from antares

### ISSUE THREAD

**Issue by Langleu** [schul-cloud/schulcloud-content-crawler#69]

**Comment by niccokunzmann** [comment]
@sebastiankliem Do you know where I can get the antares secrests from?
What are they useful for? Access or just rate limiting?

**Comment by Langleu** [comment]
@niccokunzmann ping me for the secrets.
The secrets are needed for access to a content pool of a specific federal state.

**Comment by niccokunzmann** [comment]
The arix-search-adapter is present: https://github.com/schul-cloud/arix-search-adapter
