### ISSUE TITLE
Issues sind unübersichtlich

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-content-crawler#73]
Es gibt eine Menge Anbieterissues.
Es gibt aber auch noch andere, die darin unter gehen.

Mögliche Lösung: Ein Label für Anbieter (z.B. "Anbieter" oder "Feature Request")

Umsetzung:

- macht es selbst oder lasst es mich machen - ich brauch dazu Schreibrechte.

**Comment by Dome-GER** [comment]
Du solltest jetzt Schreibrechte haben. Das über Labels zu regeln erscheint mir sinnvoll.

https://github.com/schulcloud/schulcloud-content-crawler/issues/72 ist allerdings auch nicht sehr aussagekräftig ;-)

**Comment by niccokunzmann** [comment]
@Dome-GER Danke, ich habe es gelabelt.
